image: maven:3.8.4-openjdk-17-slim

stages:
  - dependency
  - cache
  - clean_workspace
  - test
  - generate_report
  - publish_report
  - publish_extent_report

variables:
  MAVEN_OPTS: "-Xmx2048m"

before_script:
  - export DISPLAY=:0.0
  # Install Allure command-line tool
  - sudo apt-get install libpci-dev
  - sudo apt-get install nvidia-driver
  - sudo apt-get install xvfb
  - apt-get update && apt-get install -y wget unzip
  - wget https://github.com/allure-framework/allure2/releases/download/2.17.2/allure-2.17.2.zip -O allure.zip
  - unzip allure.zip -d /opt/
  - export PATH=$PATH:/opt/allure-2.17.2/bin  # Add Allure to PATH  
  - echo "Updating and installing necessary packages..."

  # Install Firefox and GeckoDriver
  # Install Firefox (latest stable version)
  - apt-get install -y firefox-esr

  # Install dependencies for GeckoDriver and unzip
  - apt-get install -y wget unzip

  # Download and install GeckoDriver (latest version)
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.32.0/geckodriver-v0.32.0-linux64.tar.gz
  - tar -xvzf geckodriver-v0.32.0-linux64.tar.gz
  - mv geckodriver /usr/local/bin/
  - chmod +x /usr/local/bin/geckodriver

  # You can specify additional dependencies or updates here if necessary.

cache:
  paths:
    - .m2/repository/

# Job to run dependency:tree
dependency:
  stage: dependency
  script:
    - mvn dependency:tree
  tags:
    - "Ewf Wns Automation"

clean_workspace:
  stage: clean_workspace
  script:
    - echo "Cleaning workspace..."
    # - rm -rf *
  tags:
    - "Ewf Wns Automation"

# Job to run tests
run_tests:
  stage: test
  script:
    - echo "Running tests with Firefox..."
    - mvn clean compile
    - cat src/main/resources/config.properties
    - mvn test
  artifacts:
    paths:
      - target/surefire-reports/*.xml
  tags:
    - "Ewf Wns Automation"

generate_report:
  stage: generate_report
  script:
    - echo "Generating Allure report..."
    - mvn allure:serve
  tags:
    - "Ewf Wns Automation"

publish_report:
  stage: publish_report
  script:
    - echo "Publishing Allure report..."
    - allure generate target/allure-results --clean -o target/allure-report
  artifacts:
    paths:
      - target/allure-report
  tags:
    - "Ewf Wns Automation"

publish_extent_report:
  stage: publish_extent_report
  script:
    - echo "Publishing Extent Report..."
  artifacts:
    paths:
      - report-output/extentreport.html
  tags:
    - ""

after_script:
  - echo "Cleaning up..."
