image: maven:3.8.6-jdk-8
stages:
  - clean_workspace
  - git
  - variables
  - before_script
  - test
  - generate_report
  - publish_report
  - publish_extent_report

variables:
  MAVEN_OPTS: "-Xmx2048m"

before_script:
  # Install Allure command-line tool
  - apt-get update && apt-get install -y wget unzip
  - wget https://github.com/allure-framework/allure2/releases/download/2.17.2/allure-2.17.2.zip -O allure.zip
  - unzip allure.zip -d /opt/
  - export PATH=$PATH:/opt/allure-2.17.2/bin  # Add Allure to PATH  
  - echo "Updating and installing necessary packages..."
  - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -

    # Add Google Chrome's repository
  - sh -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'

    # Update apt repositories
  - apt-get update -y

    # Install Google Chrome (stable version)
  - apt-get install -y google-chrome-stable

    # Install dependencies for ChromeDriver and unzip
  - apt-get install -y chromium

    # Download and install ChromeDriver (latest version for Chrome 114 in this case)
  - wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - mv chromedriver /usr/local/bin/
  - chmod +x /usr/local/bin/chromedriver

clean_workspace:
  stage: clean_workspace
  script:
    - echo "Cleaning workspace..."
    # - rm -rf *

git:
  stage: git
  script:
    - echo "Cloning repository and getting dependencies..."
    # - git clone https://github.com/MeghaShuk/ewf.git
    - mvn dependency:tree

variables:
  BASE_URL: ""
  WORKERNODE_MANAGE: ""
  LOGIN_EMAIL: ""
  LOGIN_PASSWORD: ""
  NODE_NAME: ""
  MNEMONIC: ""
  SOLUTION: ""

# Load properties from config.properties into environment variables
before_script:
  - echo "Loading properties from config.properties into environment variables..."
  - export BASE_URL=$(grep 'baseURL' src/main/resources/config.properties | cut -d'=' -f2)
  - export WORKERNODE_MANAGE=$(grep 'workernode_manage' src/main/resources/config.properties | cut -d'=' -f2)
  - export LOGIN_EMAIL=$(grep 'login_email' src/main/resources/config.properties | cut -d'=' -f2)
  - export LOGIN_PASSWORD=$(grep 'login_password' src/main/resources/config.properties | cut -d'=' -f2)
  - export NODE_NAME=$(grep 'NodeName' src/main/resources/config.properties | cut -d'=' -f2)
  - export MNEMONIC=$(grep 'Mnemonic' src/main/resources/config.properties | cut -d'=' -f2)
  - export SOLUTION=$(grep 'solution' src/main/resources/config.properties | cut -d'=' -f2)

test:
  stage: test
  script:
    - echo "Running tests..."
    - mvn clean compile
    - ls target/classes
    - cat target/classes/config.properties
    - mvn test
    - echo "Running tests with environment variables:"
    - echo "BASE_URL=$BASE_URL"
    - echo "WORKERNODE_MANAGE=$WORKERNODE_MANAGE"
    - echo "LOGIN_EMAIL=$LOGIN_EMAIL"
    - echo "LOGIN_PASSWORD=$LOGIN_PASSWORD"
    - echo "NODE_NAME=$NODE_NAME"
    - echo "MNEMONIC=$MNEMONIC"
    - echo "SOLUTION=$SOLUTION"
    #- mvn clean test -DbaseURL=$baseURL -Dworkernode_manage=$workernode_manage -Dlogin_email=$login_email -Dlogin_password=$login_password -DNodeName=$Mnemonic -Dlogin_password=$Mnemonic -Dsolution=$solution
  artifacts:
    paths:
      - target/surefire-reports/*.xml

generate_report:
  stage: generate_report
  script:
    - echo "Generating Allure report..."
    - mvn allure:serve

publish_report:
  stage: publish_report
  script:
    - echo "Publishing Allure report..."
    - allure generate target/allure-results --clean -o target/allure-report
  artifacts:
    paths:
      - target/allure-report

publish_extent_report:
  stage: publish_extent_report
  script:
    - echo "Publishing Extent Report..."
  artifacts:
    paths:
      - report-output/extentreport.html

after_script:
  - echo "Cleaning up..."

