image: maven:3.8.6-jdk-8
stages:
  - clean_workspace
  - git
  - run_tests
  - test
  - generate_report
  - publish_report
  - publish_extent_report

variables:
  MAVEN_OPTS: "-Xmx2048m"

before_script:
  # Install Allure command-line tool
  - apt-get update && apt-get install -y wget unzip
  - wget https://github.com/allure-framework/allure2/releases/download/2.17.2/allure-2.17.2.zip -O allure.zip
  - unzip allure.zip -d /opt/
  - export PATH=$PATH:/opt/allure-2.17.2/bin  # Add Allure to PATH  
  - echo "Updating and installing necessary packages..."
  - echo "Updating and installing necessary packages..."
  - wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | apt-key add -
  - sh -c 'echo "deb [arch=amd64] https://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google-chrome.list'
  - apt-get update -y
  - apt-get install -y wget unzip chromium
  - wget https://chromedriver.storage.googleapis.com/131.0.6778.85/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip
  - mv chromedriver /usr/local/bin/
  - chmod +x /usr/local/bin/chromedriver

clean_workspace:
  stage: clean_workspace
  script:
    - echo "Cleaning workspace..."
    # - rm -rf *

git:
  stage: git
  script:
    - echo "Cloning repository and getting dependencies..."
    # - git clone https://github.com/MeghaShuk/ewf.git
    - mvn dependency:tree

run_tests:
  stage: run_tests
  script:
    - echo "Running tests..."
    - mvn clean compile

test:
  stage: test
  script:
    - echo "Running JUnit tests..."
    - mvn test -DconfigFile=src/main/resources/Configuration/config.properties
  artifacts:
    paths:
      - target/surefire-reports/*.xml

generate_report:
  stage: generate_report
  script:
    - echo "Generating Allure report..."
    - mvn allure:serve

publish_report:
  stage: publish_report
  script:
    - echo "Publishing Allure report..."
    - allure generate target/allure-results --clean -o target/allure-report
  artifacts:
    paths:
      - target/allure-report

publish_extent_report:
  stage: publish_extent_report
  script:
    - echo "Publishing Extent Report..."
  artifacts:
    paths:
      - report-output/extentreport.html

after_script:
  - echo "Cleaning up..."

